### ISSUE TITLE
Support for feedback/variables

### ISSUE THREAD

**Issue by lpdswe** [bitfocus/companion-module-soundtrack-remote#10]
Hi,

Would it be possible to add support for feedback and variables, like:

- Current song & artist playing in zone
- Active playlist or station
- Track duration / % played / time remaining

We needed to switch from Spotify to Soundtrack your brand as Spotify isnt legal to use in the business scene. I really miss the feedbacks :)

Thanks!

**Comment by elliotmatson** [comment]
Yea I can look into it!

**Comment by WillieDaWonka** [comment]
Bumping this as we are moving forward to a more streamline approach in our live events venue. Feedback based on variables would be great like Spotify does. Thanks heaps!

**Comment by elliotmatson** [comment]
Still working on this. I you want to try out variables, theres a branch on this repo where I've added variables from Soundtrack. A few things to note: 
- Getting playback progress and upcoming songs are still marked as experimental on the Soundtrack API docs, so these are very much subject to change/break
- Right now, the `playback_progress_s` variable only updates when Soundtrack sends an update, which is on any playback change. I'll need to create a timer that calculates the value of `playback_progress_s` every second while the status is playing
- I haven't started on feedbacks yet, any particular requests here?

Here's the list of variables available currently:
```
   {
      variableId: "playback_state",
      name: "Playback State",
    },
    {
      variableId: "playback_volume",
      name: "Playback Volume",
    },
    {
      variableId: "playback_progress_s",
      name: "Playback Progress (s)",
    },
    {
      variableId: "playback_mode",
      name: "Playback Mode",
    },
    {
      variableId: "current_track_start",
      name: "Current Track Start Time",
    },
    {
      variableId: "current_track_id",
      name: "Current Track ID",
    },
    {
      variableId: "current_track_title",
      name: "Current Track Title",
    },
    {
      variableId: "current_track_version",
      name: "Current Track Version",
    },
    {
      variableId: "current_track_duration_s",
      name: "Current Track Duration (s)",
    },
    {
      variableId: "current_track_explicit",
      name: "Current Track is Explicit",
    },
    {
      variableId: "current_track_recognizability",
      name: "Current Track Recognizability",
    },
    {
      variableId: "current_track_album_id",
      name: "Current Track Album ID",
    },
    {
      variableId: "current_track_album_title",
      name: "Current Track Album Title",
    },
    {
      variableId: "current_track_artist_ids",
      name: "Current Track Artist IDs",
    },
    {
      variableId: "current_track_artist_names",
      name: "Current Track Artist Names",
    },
    {
      variableId: "current_track_source_type",
      name: "Current Track Source Type",
    },
    {
      variableId: "current_track_schedule_id",
      name: "Current Track Schedule ID",
    },
    {
      variableId: "current_track_schedule_title",
      name: "Current Track Schedule Title",
    },
    {
      variableId: "current_track_schedule_description",
      name: "Current Track Schedule Description",
    },
    {
      variableId: "current_track_playlist_id",
      name: "Current Track Playlist ID",
    },
    {
      variableId: "current_track_playlist_title",
      name: "Current Track Playlist Title",
    },
    {
      variableId: "current_track_playlist_description",
      name: "Current Track Playlist Description",
    },
    {
      variableId: "upcoming_track_start",
      name: "Upcoming Track Start Time",
    },
    {
      variableId: "upcoming_track_id",
      name: "Upcoming Track ID",
    },
    {
      variableId: "upcoming_track_title",
      name: "Upcoming Track Title",
    },
    {
      variableId: "upcoming_track_version",
      name: "Upcoming Track Version",
    },
    {
      variableId: "upcoming_track_duration_s",
      name: "Upcoming Track Duration (s)",
    },
    {
      variableId: "upcoming_track_explicit",
      name: "Upcoming Track is Explicit",
    },
    {
      variableId: "upcoming_track_recognizability",
      name: "Upcoming Track Recognizability",
    },
    {
      variableId: "upcoming_track_album_id",
      name: "Upcoming Track Album ID",
    },
    {
      variableId: "upcoming_track_album_title",
      name: "Upcoming Track Album Title",
    },
    {
      variableId: "upcoming_track_artist_ids",
      name: "Upcoming Track Artist IDs",
    },
    {
      variableId: "upcoming_track_artist_names",
      name: "Upcoming Track Artist Names",
    },
    {
      variableId: "upcoming_track_source_type",
      name: "Upcoming Track Source Type",
    },
    {
      variableId: "upcoming_track_schedule_id",
      name: "Upcoming Track Schedule ID",
    },
    {
      variableId: "upcoming_track_schedule_title",
      name: "Upcoming Track Schedule Title",
    },
    {
      variableId: "upcoming_track_schedule_description",
      name: "Upcoming Track Schedule Description",
    },
    {
      variableId: "upcoming_track_playlist_id",
      name: "Upcoming Track Playlist ID",
    },
    {
      variableId: "upcoming_track_playlist_title",
      name: "Upcoming Track Playlist Title",
    },
    {
      variableId: "upcoming_track_playlist_description",
      name: "Upcoming Track Playlist Description",
    },
```

**Comment by elliotmatson** [comment]
Alright, I have some rough structure in for calculating playback status, might have some bugs, but feel free to test!

**Comment by elliotmatson** [comment]
@lpdswe @WillieDaWonka Ok, I added some feedbacks. Could y'all download that branch and test it before I release it as v2.0.0? Here's the full changelog:

**V2.0.0**
- Adds subscription to Soundtrack API for real-time updates
- Now downloads a user's playlists, schedules, and stations for easier selection
- Adds support for actions:
  - Assign Playlist (by name)
  - Assign Schedule (by name)
- Adds support for feedbacks:
  - Change style based on playback state (Offline, Playing, Paused, Unpaired)
  - Change style based on playback mode (Auto, Linear, Shuffle)
  - Change style based on playback source type (Playlist, Schedule, Manually Queued)
  - Change style based on playback source playlist
  - Change style based on playback source schedule
  - Change style based on current track explicit content
  - Change style based on current track ID
  - Change style based on current track name
  - Change style based on upcoming track explicit content
  - Change style based on upcoming track ID
  - Change style based on upcoming track name
- Adds support for variables:
  - Playback state (Offline, Playing, Paused, Unpaired)
  - Playback Volume (0-16)
  - Playback Progress (s)
  - Playback Progress (%)
  - Playback Remaining (s)
  - Playback Remaining (%)
  - Playback Mode (Auto, Linear, Shuffle)
  - Current Track Start Time (UTC)
  - Current Track ID
  - Current Track Title
  - Current Track Version (radio edit, etc.)
  - Current Track Duration (s)
  - Current Track Explicit (true, false)
  - Current Track Recognizeability (0-100)
  - Current Track Album ID
  - Current Track Album Title
  - Current Track Artist ID's
  - Current Track Artist Names
  - Current Track Source Type
  - Current Track Source Schedule ID
  - Current Track Source Schedule Title
  - Current Track Source Schedule Description
  - Current Track Source Playlist ID
  - Current Track Source Playlist Title
  - Current Track Source Playlist Description
  - Upcoming Track Start Time (UTC)
  - Upcoming Track ID
  - Upcoming Track Title
  - Upcoming Track Version (radio edit, etc.)
  - Upcoming Track Duration (s)
  - Upcoming Track Explicit (true, false)
  - Upcoming Track Recognizeability (0-100)
  - Upcoming Track Album ID
  - Upcoming Track Album Title
  - Upcoming Track Artist ID's
  - Upcoming Track Artist Names
  - Upcoming Track Source Type
  - Upcoming Track Source Schedule ID
  - Upcoming Track Source Schedule Title

**Comment by WillieDaWonka** [comment]
@elliotmatson Hey mate, I haven't stress tested all your new updates, but can confirm it does pull data from the API and so far I've only tested the following due to a hectic season:

Works:
- Playback State (Playing)
- Playback State (Paused)
- Playback Source (Playlist)
- $(PLAYERNAME:playback_remaining_s) variable

Not working for me:
- Playback Source (Schedule)

Feature Request:
$(PLAYERNAME:playback_remaining) variable
pretty formatting like the Spotify module has using HH:MM:SS format

**Comment by WillieDaWonka** [comment]
Just an update: I've recently been struggling with connection stability between Companion and Soundtrack. Finally managed to get a log reading.

Log below:
error: C:\Users\USER\Documents\companion-module-dev\companion-module-soundtrack-remote-add-variables-feedbacks\main.js:202
            if (result.data.playbackUpdate["playback"] && result.data.playbackUpdate.playback.soundZone === this.config.zone_id) {
                                          ^

TypeError: Cannot read properties of null (reading 'playback')
    at C:\Users\USER\Documents\companion-module-dev\companion-module-soundtrack-remote-add-variables-feedbacks\main.js:202:43
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.20.4
Starting up module class: SoundtrackInstance
Sentry disabled
error: Module registration failed Error: Call timed out
    at IpcWrapper.sendWithCb (C:\Users\USER\Documents\companion-module-dev\companion-module-soundtrack-remote-add-variables-feedbacks\node_modules\@companion-module\base\dist\host-api\ipc-wrapper.js:35:30)
    at C:\Users\USER\Documents\companion-module-dev\companion-module-soundtrack-remote-add-variables-feedbacks\node_modules\@companion-module\base\dist\entrypoint.js:97:24

**Comment by elliotmatson** [comment]
I think i've fixed the reliability issue, and I added MM:SS and HH:MM:SS variables. What was the issue you were seeing with playing a schedule? It seems to trigger playback for me. The only issue I could see is that if there isn't any music scheduled to play on the schedule, none of the variables would change, since the current schedule is tied to the active song

**Comment by WillieDaWonka** [comment]
>What was the issue you were seeing with playing a schedule? It seems to trigger playback for me.

Mine was quite flaky, it worked once then never again, but I'm chalking that up to another operator changing the schedule around the same time I pushed the button.

**Comment by elliotmatson** [comment]
Ok interesting. Give the latest branch a shot, I added a bit more error handling in case the module gets unexpected or empty data from Soundtrack. I'm also working on adding Announcements at Soundtracks request, but those don't seem to be working yet

**Comment by WillieDaWonka** [comment]
Finally had time to update the module (love back to back EOY events with the same song requests). After updating to the latest module, it constantly refreshes instead. Every so often I'd get a chance to actually change some input fields and I've changed the zone ID to "", save then pick from the dropdown menu. Still no dice and module is completely broken

> error: C:\Program Files\Companion\companion-module-soundtrack-remote-add-variables-feedbacks\node_modules\graphql-request\dist\index.js:416
                        throw new types_1.ClientError(__assign(__assign({}, errorResult), { status: response.status, headers: response.headers }), { query: query, variables: variables });
                              ^

> ClientError: Account does not have the feature enabled, please contact support: {"response":{"data":null,"errors":[{"message":"Account does not have the feature enabled, please contact support","path":["getAccountAnnouncements"],"extensions":{"code":"UNAUTHENTICATED","exception":{"message":"Unauthenticated"}}}],"status":200,"headers":{}},"request":{"query":"query { \n          getAccountAnnouncements(accountId: \"QWNjb3VudCwsMW1teWU5M2d0Zmsv\") {\n            id\n            name\n          }\n        }"}}
    at C:\Program Files\Companion\companion-module-soundtrack-remote-add-variables-feedbacks\node_modules\graphql-request\dist\index.js:416:31
    at step (C:\Program Files\Companion\companion-module-soundtrack-remote-add-variables-feedbacks\node_modules\graphql-request\dist\index.js:67:23)
    at Object.next (C:\Program Files\Companion\companion-module-soundtrack-remote-add-variables-feedbacks\node_modules\graphql-request\dist\index.js:48:53)
    at fulfilled (C:\Program Files\Companion\companion-module-soundtrack-remote-add-variables-feedbacks\node_modules\graphql-request\dist\index.js:39:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  response: {
    data: null,
    errors: [
      {
        message: 'Account does not have the feature enabled, please contact support',
        path: [ 'getAccountAnnouncements' ],
        extensions: {
          code: 'UNAUTHENTICATED',
          exception: { message: 'Unauthenticated' }
        }
      }
    ],
    status: 200,
    headers: Headers {
      [Symbol(map)]: [Object: null prototype] {
        date: [ 'Sat, 07 Dec 2024 06:29:38 GMT' ],
        'content-type': [ 'application/json' ],
        'transfer-encoding': [ 'chunked' ],
        connection: [ 'close' ],
        'x-ratelimiting-cost': [ '2' ],
        'x-ratelimiting-tokens-available': [ '4988' ],
        'x-envoy-upstream-service-time': [ '165' ],
        'content-encoding': [ 'gzip' ],
        vary: [ 'Accept-Encoding' ],
        'cf-cache-status': [ 'DYNAMIC' ],
        'strict-transport-security': [ 'max-age=2592000; includeSubDomains' ],
        'x-content-type-options': [ 'nosniff' ],
        server: [ 'cloudflare' ],
        'cf-ray': [ '8ee276624ee95f25-SYD' ],
        'alt-svc': [ 'h3=":443"; ma=86400' ]
      }
    }
  },
  request: {
    query: 'query { \n' +
      '          getAccountAnnouncements(accountId: "QWNjb3VudCwsMW1teWU5M2d0Zmsv") {\n' +
      '            id\n' +
      '            name\n' +
      '          }\n' +
      '        }',
    variables: undefined
  }
}

> Node.js v18.20.5

> Starting up module class: SoundtrackInstance
Sentry disabled
error: Error getting config fields: Call timed out
error: Error getting config fields: Call timed out
error: Error getting config fields: Call timed out
error: Module registration failed Error: Call timed out
    at IpcWrapper.sendWithCb (C:\Program Files\Companion\companion-module-soundtrack-remote-add-variables-feedbacks\node_modules\@companion-module\base\dist\host-api\ipc-wrapper.js:35:30)
    at C:\Program Files\Companion\companion-module-soundtrack-remote-add-variables-feedbacks\node_modules\@companion-module\base\dist\entrypoint.js:97:24
Starting up module class: SoundtrackInstance
Sentry disabled
error: Module registration failed Error: Call timed out
    at IpcWrapper.sendWithCb (C:\Program Files\Companion\companion-module-soundtrack-remote-add-variables-feedbacks\node_modules\@companion-module\base\dist\host-api\ipc-wrapper.js:35:30)
    at C:\Program Files\Companion\companion-module-soundtrack-remote-add-variables-feedbacks\node_modules\@companion-module\base\dist\entrypoint.js:97:24
Starting up module class: SoundtrackInstance
Sentry disabled

**Comment by elliotmatson** [comment]
Ah, that looks like its from the new Announcements features I was trying to add. I'll have to add a check to make sure your account has that feature before it attempts to get any info from the API

**Comment by WillieDaWonka** [comment]
Unfortunately as of now, the module would not run at all, so a fix would be appreciated

**Comment by elliotmatson** [comment]
I just added a temp fix that should get things working for now. I'm not sure if there's a valid way to check if an account has the announcements feature, so I just added a try/catch block until I hear back from Soundtrack

**Comment by elliotmatson** [comment]
@WillieDaWonka Were you able to test this? Unfortunately I don't have access to an account without announcements enabled, so I can't test that error handling at all. STYB also confirmed that there isn't an API endpoint to check if an account has Announcements or not, so this is probably going to be the final implementation

**Comment by WillieDaWonka** [comment]
@elliotmatson Hey, I've finally got it running in prod. The error handling for not having announcements enabled is working as expected. but there are other little quirks with the build too:

occasionally the module crashes and wouldn't restart automatically.
temp-fix: trigger every 10 minutes to disable and enable module

sometimes I notice the variables not always working properly, namely the time remaining (MM:SS).
temp-fix: as above
![Image](https://github.com/user-attachments/assets/b3078c50-beca-4af8-a046-55f9adc80985)

`Upcoming_Track_xxx_ID` variable and feedback doesn't reliably update when a new playlist/schedule is queued until the module is restarted/next track is played.
temp-fix: buttons to queue playlists/schedules has a built in module restart
![Image](https://github.com/user-attachments/assets/21b9e5be-36f1-4549-b814-dca0aa2afa96)
OR adding in a `Logic:AND` with `Upcoming_Playback_Source`
This is a workaround
![Image](https://github.com/user-attachments/assets/e96f8745-7de1-4360-a435-52c4af9a7505)
For if this doesn't work
![Image](https://github.com/user-attachments/assets/b4e7915f-8c4b-48ea-aa20-96a51501887b)

Logs are filled with unneeded debug message as well
![Image](https://github.com/user-attachments/assets/ef8dd87e-4d27-4291-8d36-7f64f3fbba75)

might be a few more things here and there, but I won't be able to get logs to catch these anomalies for awhile.

**Comment by elliotmatson** [comment]
Did you see any kind of error message or logs when it crashed? And what OS / version of Companion? I haven't seen that on my end. 

I'll look into the other 2 issues. I'm not sure that Soundtrack will send an update when a new playlist is queued though, so the only way to fix that might be polling, which could trigger rate-limiting on their end

**Comment by elliotmatson** [comment]
I'll keep it running on another monitor while I'm working today. I was able to reproduce the issues with the upcoming track name, but unfortunately that seems to be an issue with Soundtrack's API. I receive an update when I cue another playlist, but the upcoming song in that update is incorrect. I'll follow up with them.

I haven't yet been able to reproduce the crashing or the wrong remaining time, but I'll keep an eye out

**Comment by elliotmatson** [comment]
@WillieDaWonka Have you been able to reproduce these issues at all? I haven't been able to reproduce them on my machine (macOS 15.3, Companion 3.5.1)
